project:
  type: book
  output-dir: docs

book:
  title: "나의 통계학" 
  author: "박성일"
  date: "2024. 6. 30."
  chapters:
    - index.qmd
    - part: 01_descriptive_statistics.qmd
      chapters:
        - 01_descriptive_statistics/scale_of_data.qmd
        - 01_descriptive_statistics/freq_table.qmd
        - 01_descriptive_statistics/pareto_plot.qmd
        - 01_descriptive_statistics/sigma.qmd
        - 01_descriptive_statistics/mean.qmd
    
    - part: 02_correlation.qmd
      chapters:
        - 02_correlation/pearson_correlation.qmd


format:
  html:
    theme: cosmo
    code-fold: true
    code-summary: "코드 보기"

    
  pdf:
    documentclass: scrreprt

editor: visual

