project:
  type: book
  output-dir: docs

book:
  title: "나의 통계학" 
  author: "박성일"
  date: "2024. 6. 30."
  chapters:
    - index.qmd
    - part: 01_descriptive_statistics.qmd
      chapters:
        - 01_descriptive_statistics/01_scale_of_data.qmd
        - 01_descriptive_statistics/02_freq_table.qmd
        - 01_descriptive_statistics/03_pareto_plot.qmd
        - 01_descriptive_statistics/04_sigma.qmd
        - 01_descriptive_statistics/05_mean.qmd
        - 01_descriptive_statistics/06_mean_freq_table.qmd
        - 01_descriptive_statistics/07_representative_value.qmd
        - 01_descriptive_statistics/08_standarize.qmd

    
    - part: 02_correlation.qmd
      chapters:
        - 02_correlation/pearson_correlation.qmd


format:
  html:
    theme: cosmo
    code-fold: true
    code-summary: "코드 보기"

    
  pdf:
    documentclass: scrreprt

editor: visual

